name: Deploy Firebase Functions

on:
  push:
    paths:
      - 'backend/**' # Trigger this workflow only for changes in the backend directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Write Service Account JSON to File
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/service-account.json

    - name: Verify Service Account File Exists
      run: ls -l $HOME/service-account.json

    - name: Output Service Account File Content
      run: cat $HOME/service-account.json

    - name: Adjust Permissions for Service Account File
      run: chmod 600 $HOME/service-account.json

    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file=$HOME/service-account.json

    - name: Set Firebase Functions Config
      run: firebase functions:config:set google.application_credentials="projects/canvas-app-production/secrets/firebase-service-account-key/versions/latest" --project canvas-app-production

    - name: Deploy Functions
      working-directory: backend/functions
      run: firebase deploy --only functions
