name: Deploy Firebase Functions

on:
  push:
    paths:
      - 'backend/**'  # Trigger for changes in the backend directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Create Service Account JSON file
      run: |
        echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_CONTENT }} > $HOME/service-account.json
        cat $HOME/service-account.json  # To check if the file was created properly
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json
        chmod 644 $HOME/service-account.json
        gcloud auth activate-service-account --key-file=$HOME/service-account.json
        firebase projects:list --project canvas-app-production
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/service-account.json

    - name: Set Firebase Functions Config
      run: |
        firebase functions:config:set google.application_credentials="projects/canvas-app-production/secrets/firebase-service-account-key/versions/latest" --project canvas-app-production
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/service-account.json

    - name: Deploy Firebase Functions
      working-directory: backend/functions
      run: |
        firebase deploy --only functions --project canvas-app-production
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/service-account.json

    - name: Clean Up
      run: |
        rm $HOME/service-account.json
