name: Deploy Firebase Functions

on:
  push:
    paths:
      - 'backend/**' # Trigger this workflow only for changes in the backend directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: canvas-app-production 
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Set Firebase Functions Config
      run: firebase functions:config:set google.application_credentials="projects/canvas-app-production/secrets/firebase-service-account-key/versions/latest" --project canvas-app-production
      with:
        project_id: canvas-app-production 
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Deploy Functions
      working-directory: backend/functions
      run: firebase deploy --only functions
